pub mod chatterbox;
pub mod edge_tts;
pub mod fasterwhisper;
#[cfg(target_os = "macos")]
pub mod fish_speech;
#[cfg(target_os = "macos")]
pub mod mlx_audio;
#[cfg(target_os = "macos")]
pub mod mlx_whisper;
#[cfg(target_os = "macos")]
pub mod qwen3_tts;
pub mod whispercpp;
pub mod whisperkit;
