use serde::{Deserialize, Serialize};
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum LanguageCode {
    #[serde(rename = "zh_cn")] ZhCn,
    #[serde(rename = "zh_tw")] ZhTw,
    #[serde(rename = "en")] En,
    #[serde(rename = "ja")] Ja,
    #[serde(rename = "ko")] Ko,
    #[serde(rename = "ru")] Ru,
    #[serde(rename = "fr")] Fr,
    #[serde(rename = "de")] De,
    #[serde(rename = "es")] Es,
    #[serde(rename = "pt")] Pt,
    #[serde(rename = "it")] It,
    #[serde(rename = "nl")] Nl,
    #[serde(rename = "pl")] Pl,
    #[serde(rename = "tr")] Tr,
    #[serde(rename = "ar")] Ar,
    #[serde(rename = "th")] Th,
    #[serde(rename = "vi")] Vi,
    #[serde(rename = "id")] Id,
    #[serde(rename = "ms")] Ms,
    #[serde(rename = "hi")] Hi,
    #[serde(rename = "bn")] Bn,
    #[serde(rename = "ta")] Ta,
    #[serde(rename = "te")] Te,
    #[serde(rename = "uk")] Uk,
    #[serde(rename = "el")] El,
    #[serde(rename = "cs")] Cs,
    #[serde(rename = "ro")] Ro,
    #[serde(rename = "hu")] Hu,
    #[serde(rename = "sv")] Sv,
    #[serde(rename = "da")] Da,
    #[serde(rename = "fi")] Fi,
    #[serde(rename = "no")] No,
    #[serde(rename = "sk")] Sk,
    #[serde(rename = "bg")] Bg,
    #[serde(rename = "hr")] Hr,
    #[serde(rename = "sr")] Sr,
    #[serde(rename = "sl")] Sl,
    #[serde(rename = "lt")] Lt,
    #[serde(rename = "lv")] Lv,
    #[serde(rename = "et")] Et,
    #[serde(rename = "he")] He,
    #[serde(rename = "fa")] Fa,
    #[serde(rename = "ur")] Ur,
    #[serde(rename = "sw")] Sw,
    #[serde(rename = "af")] Af,
    #[serde(rename = "tl")] Tl,
    #[serde(rename = "my")] My,
    #[serde(rename = "km")] Km,
    #[serde(rename = "ka")] Ka,
    #[serde(rename = "az")] Az,
    #[serde(rename = "kk")] Kk,
    #[serde(rename = "uz")] Uz,
    #[serde(rename = "mn")] Mn,
    #[serde(rename = "ne")] Ne,
    #[serde(rename = "si")] Si,
    #[serde(rename = "lo")] Lo,
    #[serde(rename = "ca")] Ca,
    #[serde(rename = "gl")] Gl,
    #[serde(rename = "eu")] Eu,
    #[serde(rename = "mk")] Mk,
    #[serde(rename = "sq")] Sq,
    #[serde(rename = "hy")] Hy,
    #[serde(rename = "bs")] Bs,
    #[serde(rename = "is")] Is,
    #[serde(rename = "mt")] Mt,
    #[serde(rename = "cy")] Cy,
    #[serde(rename = "ga")] Ga,
    #[serde(rename = "la")] La,
    #[serde(rename = "jv")] Jv,
    #[serde(rename = "su")] Su,
    #[serde(rename = "am")] Am,
    #[serde(rename = "yo")] Yo,
    #[serde(rename = "ig")] Ig,
    #[serde(rename = "zu")] Zu,
    #[serde(rename = "ha")] Ha,
    #[serde(rename = "so")] So,
    #[serde(rename = "mg")] Mg,
    #[serde(rename = "pa")] Pa,
    #[serde(rename = "gu")] Gu,
    #[serde(rename = "mr")] Mr,
    #[serde(rename = "kn")] Kn,
    #[serde(rename = "ml")] Ml,
}

impl LanguageCode {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::ZhCn => "zh_cn", Self::ZhTw => "zh_tw", Self::En => "en",
            Self::Ja => "ja", Self::Ko => "ko", Self::Ru => "ru",
            Self::Fr => "fr", Self::De => "de", Self::Es => "es",
            Self::Pt => "pt", Self::It => "it", Self::Nl => "nl",
            Self::Pl => "pl", Self::Tr => "tr", Self::Ar => "ar",
            Self::Th => "th", Self::Vi => "vi", Self::Id => "id",
            Self::Ms => "ms", Self::Hi => "hi", Self::Bn => "bn",
            Self::Ta => "ta", Self::Te => "te", Self::Uk => "uk",
            Self::El => "el", Self::Cs => "cs", Self::Ro => "ro",
            Self::Hu => "hu", Self::Sv => "sv", Self::Da => "da",
            Self::Fi => "fi", Self::No => "no", Self::Sk => "sk",
            Self::Bg => "bg", Self::Hr => "hr", Self::Sr => "sr",
            Self::Sl => "sl", Self::Lt => "lt", Self::Lv => "lv",
            Self::Et => "et", Self::He => "he", Self::Fa => "fa",
            Self::Ur => "ur", Self::Sw => "sw", Self::Af => "af",
            Self::Tl => "tl", Self::My => "my", Self::Km => "km",
            Self::Ka => "ka", Self::Az => "az", Self::Kk => "kk",
            Self::Uz => "uz", Self::Mn => "mn", Self::Ne => "ne",
            Self::Si => "si", Self::Lo => "lo", Self::Ca => "ca",
            Self::Gl => "gl", Self::Eu => "eu", Self::Mk => "mk",
            Self::Sq => "sq", Self::Hy => "hy", Self::Bs => "bs",
            Self::Is => "is", Self::Mt => "mt", Self::Cy => "cy",
            Self::Ga => "ga", Self::La => "la", Self::Jv => "jv",
            Self::Su => "su", Self::Am => "am", Self::Yo => "yo",
            Self::Ig => "ig", Self::Zu => "zu", Self::Ha => "ha",
            Self::So => "so", Self::Mg => "mg", Self::Pa => "pa",
            Self::Gu => "gu", Self::Mr => "mr", Self::Kn => "kn",
            Self::Ml => "ml",
        }
    }

    pub fn display_name(&self) -> &'static str {
        match self {
            Self::ZhCn => "Simplified Chinese", Self::ZhTw => "Traditional Chinese",
            Self::En => "English", Self::Ja => "Japanese", Self::Ko => "Korean",
            Self::Ru => "Russian", Self::Fr => "French", Self::De => "German",
            Self::Es => "Spanish", Self::Pt => "Portuguese", Self::It => "Italian",
            Self::Nl => "Dutch", Self::Pl => "Polish", Self::Tr => "Turkish",
            Self::Ar => "Arabic", Self::Th => "Thai", Self::Vi => "Vietnamese",
            Self::Id => "Indonesian", Self::Ms => "Malay", Self::Hi => "Hindi",
            Self::Bn => "Bengali", Self::Ta => "Tamil", Self::Te => "Telugu",
            Self::Uk => "Ukrainian", Self::El => "Greek", Self::Cs => "Czech",
            Self::Ro => "Romanian", Self::Hu => "Hungarian", Self::Sv => "Swedish",
            Self::Da => "Danish", Self::Fi => "Finnish", Self::No => "Norwegian",
            Self::Sk => "Slovak", Self::Bg => "Bulgarian", Self::Hr => "Croatian",
            Self::Sr => "Serbian", Self::Sl => "Slovenian", Self::Lt => "Lithuanian",
            Self::Lv => "Latvian", Self::Et => "Estonian", Self::He => "Hebrew",
            Self::Fa => "Persian", Self::Ur => "Urdu", Self::Sw => "Swahili",
            Self::Af => "Afrikaans", Self::Tl => "Filipino", Self::My => "Burmese",
            Self::Km => "Khmer", Self::Ka => "Georgian", Self::Az => "Azerbaijani",
            Self::Kk => "Kazakh", Self::Uz => "Uzbek", Self::Mn => "Mongolian",
            Self::Ne => "Nepali", Self::Si => "Sinhala", Self::Lo => "Lao",
            Self::Ca => "Catalan", Self::Gl => "Galician", Self::Eu => "Basque",
            Self::Mk => "Macedonian", Self::Sq => "Albanian", Self::Hy => "Armenian",
            Self::Bs => "Bosnian", Self::Is => "Icelandic", Self::Mt => "Maltese",
            Self::Cy => "Welsh", Self::Ga => "Irish", Self::La => "Latin",
            Self::Jv => "Javanese", Self::Su => "Sundanese", Self::Am => "Amharic",
            Self::Yo => "Yoruba", Self::Ig => "Igbo", Self::Zu => "Zulu",
            Self::Ha => "Hausa", Self::So => "Somali", Self::Mg => "Malagasy",
            Self::Pa => "Punjabi", Self::Gu => "Gujarati", Self::Mr => "Marathi",
            Self::Kn => "Kannada", Self::Ml => "Malayalam",
        }
    }

    pub fn is_asian(&self) -> bool {
        matches!(
            self,
            Self::ZhCn | Self::ZhTw | Self::Ja | Self::Ko | Self::Th
                | Self::Vi | Self::My | Self::Km | Self::Lo
        )
    }
}

impl fmt::Display for LanguageCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
